window.saaaMembers = [
    { id: "acs-freight-services-pte-ltd", name: "ACS Freight Services Pte Ltd", letter: "A", logo: "images/members/logos/acs-freight-services-pte-ltd.jpg" },
    { id: "air-market-express-s-pte-ltd", name: "Air Market Express(s) Pte Ltd", letter: "A", logo: "images/members/logos/air-market-express-s-pte-ltd.jpg" },
    { id: "alliance-21-pte-ltd", name: "Alliance 21 Pte Ltd", letter: "A", logo: "images/members/logos/alliance-21-pte-ltd.jpg" },
    { id: "apc-asia-pacific-cargo-s-pte-ltd", name: "APC Asia Pacific Cargo (S) Pte Ltd", letter: "A", logo: "images/members/logos/apc-asia-pacific-cargo-s-pte-ltd.png" },
    { id: "asl-aviation-group-pte-ltd", name: "ASL Aviation Group Pte Ltd", letter: "A", logo: "images/members/logos/asl-aviation-group-pte-ltd.jpg" },
    { id: "aspac-aircargo-services-pte-ltd", name: "ASPAC Aircargo Services Pte Ltd", letter: "A", logo: "images/members/logos/aspac-aircargo-services-pte-ltd.jpg" },
    { id: "b-h-worldwide-sg-pte-ltd", name: "B&H Worldwide (SG) Pte Ltd", letter: "B", logo: "images/members/logos/b-h-worldwide-sg-pte-ltd.png" },
    { id: "baylink-logistics-pte-ltd", name: "Baylink Logistics Pte Ltd", letter: "B", logo: "images/members/logos/baylink-logistics-pte-ltd.jpg" },
    { id: "cargo-community-network-ccn", name: "Cargo Community Network (CCN)", letter: "C", logo: "images/members/logos/cargo-community-network-ccn.jpg" },
    { id: "cti-logistics-pte-ltd", name: "CTI Logistics Pte Ltd", letter: "C", logo: "images/members/logos/cti-logistics-pte-ltd.png" },
    { id: "declarators-pte-ltd", name: "Declarators Pte Ltd", letter: "D", logo: "images/members/logos/declarators-pte-ltd.jpg" },
    { id: "dhl", name: "DHL", letter: "D", logo: "images/members/logos/dhl.jpg" },
    { id: "dnata-singapore-pte-ltd", name: "dnata Singapore Pte Ltd", letter: "D", logo: "images/members/logos/dnata-singapore-pte-ltd.png" },
    { id: "european-cargo-services-asia-pacific-pte-ltd", name: "European Cargo Services Asia Pacific Pte Ltd", letter: "E", logo: "images/members/logos/european-cargo-services-asia-pacific-pte-ltd.png" },
    { id: "evo-logistics-pte-ltd", name: "EVO Logistics Pte Ltd", letter: "E", logo: "images/members/logos/evo-logistics-pte-ltd.png" },
    { id: "g-t-freight-forwarders-s-pte-ltd", name: "G.T. Freight Forwarders (S) Pte Ltd", letter: "G", logo: "images/members/logos/g-t-freight-forwarders-s-pte-ltd.jpg" },
    { id: "global-airfreight-international-pte-ltd", name: "Global Airfreight International Pte Ltd", letter: "G", logo: "images/members/logos/global-airfreight-international-pte-ltd.png" },
    { id: "griffin-kinetic-pte-ltd", name: "Griffin Kinetic Pte Ltd", letter: "G", logo: "images/members/logos/griffin-kinetic-pte-ltd.jpg" },
    { id: "halford-air-cargo-s-pte-ltd", name: "Halford Air Cargo (S) Pte Ltd", letter: "H", logo: "images/members/logos/halford-air-cargo-s-pte-ltd.png" },
    { id: "harbour-handlers-pte-ltd", name: "Harbour Handlers Pte Ltd", letter: "H", logo: "images/members/logos/harbour-handlers-pte-ltd.png" },
    { id: "jas-forwarding-worldwide-pte-ltd", name: "JAS Forwarding Worldwide Pte Ltd", letter: "J", logo: "images/members/logos/jas-forwarding-worldwide-pte-ltd.png" },
    { id: "jetsea-logistics-pte-ltd", name: "Jetsea Logistics Pte Ltd", letter: "J", logo: "images/members/logos/jetsea-logistics-pte-ltd.jpg" },
    { id: "k-c-dat-freight-solutions-pte-ltd", name: "K C Dat Freight Solutions Pte Ltd", letter: "K", logo: "images/members/logos/k-c-dat-freight-solutions-pte-ltd.png" },
    { id: "kuehne-nagel-in-singapore", name: "Kuehne + Nagel in Singapore", letter: "K", logo: "images/members/logos/kuehne-nagel-in-singapore.png" },
    { id: "logisteed-asia-pacific-pte-ltd", name: "LOGISTEED Asia-Pacific Pte. Ltd.", letter: "L", logo: "images/members/logos/logisteed-asia-pacific-pte-ltd.png" },
    { id: "logwin-air-ocean-singapore-pte-ltd", name: "Logwin Air + Ocean Singapore Pte Ltd", letter: "L", logo: "images/members/logos/logwin-air-ocean-singapore-pte-ltd.png" },
    { id: "mega-air-pte-ltd", name: "Mega-Air Pte Ltd", letter: "M", logo: "images/members/logos/mega-air-pte-ltd.png" },
    { id: "mercury-freight-distribution-pte-ltd", name: "Mercury Freight Distribution Pte Ltd", letter: "M", logo: "images/members/logos/mercury-freight-distribution-pte-ltd.png" },
    { id: "nnr-global-logistics-s-pte-ltd", name: "NNR Global Logistics (S) Pte Ltd", letter: "N", logo: "images/members/logos/nnr-global-logistics-s-pte-ltd.jpg" },
    { id: "ocs-courier-service-pte-ltd", name: "OCS Courier Service Pte Ltd", letter: "O", logo: "images/members/logos/ocs-courier-service-pte-ltd.png" },
    { id: "pacific-logistics-group-pte-ltd", name: "Pacific Logistics Group Pte Ltd", letter: "P", logo: "images/members/logos/pacific-logistics-group-pte-ltd.png" },
    { id: "pan-pacific-leasing-group", name: "Pan Pacific Leasing Group", letter: "P", logo: "images/members/logos/pan-pacific-leasing-group.jpg" },
    { id: "planet-logistics-pte-ltd", name: "Planet Logistics Pte Ltd", letter: "P", logo: "images/members/logos/planet-logistics-pte-ltd.png" },
    { id: "quickflo-logistics-pte-ltd", name: "Quickflo Logistics Pte Ltd", letter: "Q", logo: "images/members/logos/quickflo-logistics-pte-ltd.png" },
    { id: "rcs-logistics-singapore-pte-ltd", name: "RCS Logistics Singapore Pte Ltd", letter: "R", logo: "images/members/logos/rcs-logistics-singapore-pte-ltd.png" },
    { id: "s-f-express-pte-ltd", name: "S.F. Express Pte Ltd", letter: "S", logo: "images/members/logos/s-f-express-pte-ltd.jpg" },
    { id: "sats-airport-services-pte-ltd", name: "SATS Airport Services Pte Ltd", letter: "S", logo: "images/members/logos/sats-airport-services-pte-ltd.png" },
    { id: "scanwell-logistics-sin-pte-ltd", name: "Scanwell Logistics (SIN) Pte Ltd", letter: "S", logo: "images/members/logos/scanwell-logistics-sin-pte-ltd.png" },
    { id: "seko", name: "SEKO", letter: "S", logo: "images/members/logos/seko.png" },
    { id: "shalom-international-movers-pte-ltd", name: "Shalom International Movers Pte Ltd", letter: "S", logo: "images/members/logos/shalom-international-movers-pte-ltd.png" },
    { id: "sintop-international-pte-ltd", name: "Sintop International Pte Ltd", letter: "S", logo: "images/members/logos/sintop-international-pte-ltd.png" },
    { id: "sky-leader-freight-pte-ltd", name: "Sky Leader Freight Pte Ltd", letter: "S", logo: "images/members/logos/sky-leader-freight-pte-ltd.png" },
    { id: "skylift-consolidator-pte-ltd", name: "Skylift Consolidator (Pte) Ltd", letter: "S", logo: "images/members/logos/skylift-consolidator-pte-ltd.png" },
    { id: "speedmark-air-transportation-pte-ltd", name: "Speedmark Air Transportation Pte Ltd", letter: "S", logo: "images/members/logos/speedmark-air-transportation-pte-ltd.jpg" },
    { id: "st-logistics-pte-ltd", name: "ST Logistics Pte Ltd", letter: "S", logo: "images/members/logos/st-logistics-pte-ltd.png" },
    { id: "t-h-i-logistics-singapore", name: "T.H.I. Logistics Singapore", letter: "T", logo: "images/members/logos/t-h-i-logistics-singapore.png" },
    { id: "tfs-freight-international-pte-ltd", name: "TFS Freight International Pte Ltd", letter: "T", logo: "images/members/logos/tfs-freight-international-pte-ltd.jpg" },
    { id: "tic-traffic-international-consortium-s-pte-ltd", name: "TIC Traffic International Consortium (S) Pte Ltd", letter: "T", logo: "images/members/logos/tic-traffic-international-consortium-s-pte-ltd.jpg" },
    { id: "transpeed-cargo-s-pte-ltd", name: "Transpeed Cargo (S) Pte Ltd", letter: "T", logo: "images/members/logos/transpeed-cargo-s-pte-ltd.jpg" },
    { id: "union-air-freight-s-pte-ltd", name: "Union Air Freight (S) Pte Ltd", letter: "U", logo: "images/members/logos/union-air-freight-s-pte-ltd.png" },
    { id: "ups-pte-ltd", name: "UPS Pte Ltd", letter: "U", logo: "images/members/logos/ups-pte-ltd.png" },
    { id: "ut-ways-freight-services-pte-ltd", name: "UT-Ways Freight Services Pte Ltd", letter: "U", logo: "images/members/logos/ut-ways-freight-services-pte-ltd.png" },
    { id: "vck-vanuatu-air-s-pte-ltd", name: "VCK-Vanuatu Air (S) Pte Ltd", letter: "V", logo: "images/members/logos/vck-vanuatu-air-s-pte-ltd.png" },
    { id: "world-freight-pte-ltd", name: "World Freight Pte Ltd", letter: "W", logo: "images/members/logos/world-freight-pte-ltd.jpg" },
    { id: "yusen-logistics-pte-ltd", name: "Yusen Logistics Pte Ltd", letter: "Y", logo: "images/members/logos/yusen-logistics-pte-ltd.png" },
];
